name: Build a binary for ARM 
on: [push]
jobs:
  Make-Arm-Binary:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: prepare software for multi arch
        run: sudo apt-get install -y qemu binfmt-support qemu-user-static

      - name: reset qemu user statistics
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: make binary
        run: docker run --rm --platform linux/arm64/v8 -t -v "${PWD}:/build" arm64v8/golang /bin/bash -c "cd /build && GOOS=darwin  go build main.go"

      - uses: actions/upload-artifact@v3
        with:
          name: helloWorld
          path: main
